# Generated by Django 6.0 on 2026-01-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_consignment_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='goal_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_consignments', to='core.city'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='goal_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_consignments', to='core.country'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='start_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_consignments', to='core.city'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='start_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_consignments', to='core.country'),
        ),
    ]
