# Generated by Django 6.0 on 2026-02-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_consignment_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consignment',
            name='maxPackageSize',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consignment',
            name='not_forbidden',
            field=models.BooleanField(default=False),
        ),
    ]
