# Generated by Django 6.0 on 2026-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consignment_contact_consignment_maxpackagesize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='maxPackageSize',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
