# Generated by Django 6.0 on 2026-02-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_consignment_maxpackagesize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='not_forbidden',
            new_name='forbidden',
        ),
    ]
