# Generated by Django 6.0 on 2026-01-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consignment_goal_city_consignment_goal_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='titel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
